listen = any:8080 any:4242

403 = 403.html
404 = 404.html
MaxRequestBodySize = 100


route
{
	route = /
	methods = get post
	root = /home/dbank/Coding/Webserv/pages
	default = dfs
	directorylisting = false
}