server
{
	listen = any:4242
	MaxRequestBodySize = 1024
	route
	{
		route = /
		methods = get 
		root = /home/dbank/Coding/Webserv/pages
		default = /home/dbank/Coding/Webserv/pages/page.html
		directorylisting = true
	}

	route
	{
		route = /upload
		methods = get post delete
		root = /home/dbank/Coding/Webserv/upload
		default = /home/dbank/Coding/Webserv/pages/page.html
		directorylisting = true
	}
	route
	{
		route = /codam
		methods = get
		root = /home/dbank/Coding/Webserv/src
		default = pages/page.html
		directorylisting = false
		redirection = https://codam.nl
	}
}